song1 = Song.create(title: "Sober", released: true, release_year: 2014, artist_name: "Childish Gambino", genre: "hip-hop")
song2 = Song.create(title: "Sicko Mode", released: false, release_year: 2015, artist_name: "Travi$ Scott", genre: "trap")
song3 = Song.create(title: "Losing It", released: true, release_year: 2016, artist_name: "FISHER", genre: "techno")
song4 = Song.create(title: "Kid Cudi", released: false, release_year: 2017, artist_name: "Playboi Carti", genre: "rap")
song5 = Song.create(title: "After Hours", released: true, release_year: 2020, artist_name: "The Weeknd", genre: "r&b")